### ISSUE TITLE
Incompatible tensorboard versions cause error - AIML40

### ISSUE THREAD

**Issue by jason-theodorakopoulos** [microsoft/ignite-learning-paths-training-aiml#82] opened 2020-02-21 15:24 UTC
I get the following error when running this [notebook](https://github.com/microsoft/ignite-learning-paths-training-aiml/blob/master/aiml40/absa.ipynb).
Should I make some changes in my env configuration ?

```
Successfully built nlp-architect sklearn
ERROR: tensorflow-gpu 2.1.0 has requirement tensorboard<2.2.0,>=2.1.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: tensorflow-gpu 2.1.0 has requirement tensorflow-estimator<2.2.0,>=2.1.0rc0, but you'll have tensorflow-estimator 1.13.0 which is incompatible.
ERROR: azureml-train-automl-runtime 1.0.83.1 has requirement pandas<=0.23.4,>=0.21.0, but you'll have pandas 0.24.2 which is incompatible.
ERROR: azureml-train-automl-runtime 1.0.83.1 has requirement scipy<=1.1.0,>=1.0.0, but you'll have scipy 1.4.1 which is incompatible.
ERROR: azureml-train-automl-runtime 1.0.83.1 has requirement wheel==0.30.0, but you'll have wheel 0.33.6 which is incompatible.
ERROR: azureml-opendatasets 1.0.83 has requirement pandas<=0.23.4,>=0.21.0, but you'll have pandas 0.24.2 which is incompatible.
ERROR: azureml-opendatasets 1.0.83 has requirement scipy<=1.1.0,>=1.0.0, but you'll have scipy 1.4.1 which is incompatible.
ERROR: azureml-defaults 1.0.83 has requirement flask==1.0.3, but you'll have flask 1.1.1 which is incompatible.
ERROR: azureml-datadrift 1.0.83 has requirement matplotlib==3.0.2, but you'll have matplotlib 3.1.2 which is incompatible.
ERROR: azureml-automl-runtime 1.0.83 has requirement azureml-automl-core==1.0.83, but you'll have azureml-automl-core 1.0.83.1 which is incompatible.
ERROR: azureml-automl-runtime 1.0.83 has requirement pandas<=0.23.4,>=0.21.0, but you'll have pandas 0.24.2 which is incompatible.
ERROR: azureml-automl-runtime 1.0.83 has requirement scipy<=1.1.0,>=1.0.0, but you'll have scipy 1.4.1 which is incompatible.
ERROR: azureml-automl-runtime 1.0.83 has requirement wheel==0.30.0, but you'll have wheel 0.33.6 which is incompatible.
Installing collected packages: tensorboard, tensorflow-estimator, tensorflow, dynet, murmurhash, plac, cymem, preshed, wasabi, blis, srsly, thinc, spacy, sklearn, pandas, tensorflow-hub, nlp-architect
```

![image](https://user-images.githubusercontent.com/57361398/75046406-afa3d500-54cd-11ea-9bfa-d860c1a3842a.png)

**Comment by amynic** [comment] 2020-02-23 21:16
Hi @jason-theodorakopoulos thank you for letting us know - we will start to investigate this issue now

**Comment by amynic** [comment] 2020-02-27 16:31
Hi @jason-theodorakopoulos after testing I can confirm this is not a breaking change and absa.ipynb can still be fully run. However we will look to fix the versions so we don't see the errors shortly: 
![image](https://user-images.githubusercontent.com/13828867/75464049-89bf7a00-597e-11ea-8b3f-ec7486d26780.png)

**Comment by jason-theodorakopoulos** [comment] 2020-02-27 17:08
Great – thanks Amy

Kind Regards,
Jason

**Comment by amynic** [comment] 2020-04-15 09:13
Closing this issue - the notebooks have also been updated and cleaned again since this issue was submitted - thank you for reporting

**Closed as completed by amynic** 2020-04-15 09:13 UTC
Labels: bug, documentation, aiml40
